cookie:
  expiry_days: 7
  key: "grade_portal_secret_key"
  name: "grade_portal_cookie"

credentials:
  usernames:
    admin:
      name: "鄭右玫 老師"
      password: "123456"
      role: "admin"
    "20401":
      name: "王佑宇"
      password: "a29jrfnji"
      role: "student"
    "02":
      name: "林庭誼"
      password: "1020"
      role: "student"
    "20403":
      name: "陳泓宇"
      password: "sjih872b"
      role: "student"
    "20404":
      name: "劉建廷"
      password: "shu8erd2"
      role: "student"
    "20405":
      name: ""
      password: "0709"
      role: "student"
preauthorized:
  emails: []

